# .github/workflows/terraform-apply.yml
name: Terraform Apply

on:
  workflow_call:
    inputs:
      terraform_version:
        required: true
        type: string

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ inputs.terraform_version }}

      - name: Terraform Apply
        run: terraform apply "tfplan"
