name: tf-lint
on: 
 workflow_call:
jobs:
 lint: 
   name: terrafomf fmt
   runs-on: ubuntu-latest

   steps:
    - name: checkout the code 
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: install terraform
      uses: hashicorp/setup-terraform@v3
      with: 
       terraform_version: "1.6.4"
    - name: lint terraform
      shell: bash
      run: |
       terraform fmt --check --recursive --diff
